In [1]:
import pandas as pd

In [2]:
def load_data(filename):
    data = pd.read_csv(filename, skiprows=1)
    data.columns = ['Country','Summer','Gold Summer','Silver Summer','Bronze Summer','Total', '# Winter',
       'Gold Winter', 'Silver Winter', 'Bronze Winter', 'Total.1', '# Games', 'Gold', 'Silver',
       'Bronze', 'Combined total']
    data = data.drop(['Total','Total.1','Combined total'], axis = 1)
    data = data.drop(data.index[146])
    
    return data

In [3]:
data= load_data('olympics.csv')

In [4]:
def first_country(name):
    for i in range(146):
        if name in data.loc[i][0]:
            print(data.loc[i])

,Country,Summer,Gold Summer,Silver Summer,Bronze Summer,# Winter,Gold Winter,Silver Winter,Bronze Winter,# Games,Gold,Silver,Bronze
0,Afghanistan (AFG),13,0,0,2,0,0,0,0,13,0,0,2
1,Algeria (ALG),12,5,2,8,3,0,0,0,15,5,2,8
2,Argentina (ARG),23,18,24,28,18,0,0,0,41,18,24,28
3,Armenia (ARM),5,1,2,9,6,0,0,0,11,1,2,9
4,Australasia (ANZ) [ANZ],2,3,4,5,0,0,0,0,2,3,4,5
5,Australia (AUS) [AUS] [Z],25,139,152,177,18,5,3,4,43,144,155,181
6,Austria (AUT),26,18,33,35,22,59,78,81,48,77,111,116
7,Azerbaijan (AZE),5,6,5,15,5,0,0,0,10,6,5,15
8,Bahamas (BAH),15,5,2,5,0,0,0,0,15,5,2,5
9,Bahrain (BRN),8,0,0,1,0,0,0,0,8,0,0,1
10,Barbados (BAR) [BAR],11,0,0,1,0,0,0,0,11,0,0,1
11,Belarus (BLR),5,12,24,39,6,6,4,5,11,18,28,44
12,Belgium (BEL),25,37,52,53,20,1,1,3,45,38,53,56
13,Bermuda (BER),17,0,0,1,7,0,0,0,24,0,0,1
14,Bohemia (BOH) [BOH] [Z],3,0,1,3,0,0,0,0,3,0,1,3
15,Botswana (BOT),9,0,1,0,0,0,0,0,9,0,1,0
16,Brazil (BRA),21,23,30,55,7,0,0,0,28,23,30,55
17,British West Indies (BWI) [BWI],1,0,0,2,0,0,0,0,1,0,0,2
18,Bulgaria (BUL) [H],19,51,85,78,19,1,2,3,38,52,87,81
19,Burundi (BDI),5,1,0,0,0,0,0,0,5,1,0,0
20,Cameroon (CMR),13,3,1,1,1,0,0,0,14,3,1,1
21,Canada (CAN),25,59,99,121,22,62,56,52,47,121,155,173
22,Chile (CHI) [I],22,2,7,4,16,0,0,0,38,2,7,4
23,China (CHN) [CHN],9,201,146,126,10,12,22,19,19,213,168,145
24,Colombia (COL),18,2,6,11,1,0,0,0,19,2,6,11
25,Costa Rica (CRC),14,1,1,2,6,0,0,0,20,1,1,2
26,Ivory Coast (CIV) [CIV],12,0,1,0,0,0,0,0,12,0,1,0
27,Croatia (CRO),6,6,7,10,7,4,6,1,13,10,13,11
28,Cuba (CUB) [Z],19,72,67,70,0,0,0,0,19,72,67,70
29,Cyprus (CYP),9,0,1,0,10,0,0,0,19,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,Spain (ESP) [Z],22,37,59,35,19,1,0,1,41,38,59,36
117,Sri Lanka (SRI) [SRI],16,0,2,0,0,0,0,0,16,0,2,0
118,Sudan (SUD),11,0,1,0,0,0,0,0,11,0,1,0
119,Suriname (SUR) [E],11,1,0,1,0,0,0,0,11,1,0,1
120,Sweden (SWE) [Z],26,143,164,176,22,50,40,54,48,193,204,230
121,Switzerland (SUI),27,47,73,65,22,50,40,48,49,97,113,113
122,Syria (SYR),12,1,1,1,0,0,0,0,12,1,1,1
123,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,11,0,0,0,24,2,7,12
124,Tajikistan (TJK),5,0,1,2,4,0,0,0,9,0,1,2
125,Tanzania (TAN) [TAN],12,0,2,0,0,0,0,0,12,0,2,0
126,Thailand (THA),15,7,6,11,3,0,0,0,18,7,6,11
127,Togo (TOG),9,0,0,1,1,0,0,0,10,0,0,1
128,Tonga (TGA),8,0,1,0,1,0,0,0,9,0,1,0
129,Trinidad and Tobago (TRI) [TRI],16,2,5,11,3,0,0,0,19,2,5,11
130,Tunisia (TUN),13,3,3,4,0,0,0,0,13,3,3,4
131,Turkey (TUR),21,39,25,24,16,0,0,0,37,39,25,24
132,Uganda (UGA),14,2,3,2,0,0,0,0,14,2,3,2
133,Ukraine (UKR),5,33,27,55,6,2,1,4,11,35,28,59
134,United Arab Emirates (UAE),8,1,0,0,0,0,0,0,8,1,0,0
135,United States (USA) [P] [Q] [R] [Z],26,976,757,666,22,96,102,84,48,1072,859,750
136,Uruguay (URU),20,2,2,6,1,0,0,0,21,2,2,6
137,Uzbekistan (UZB),5,5,5,10,6,1,0,0,11,6,5,10
138,Venezuela (VEN),17,2,2,8,4,0,0,0,21,2,2,8
139,Vietnam (VIE),14,0,2,0,0,0,0,0,14,0,2,0
140,Virgin Islands (ISV),11,0,1,0,7,0,0,0,18,0,1,0
141,Yugoslavia (YUG) [YUG],16,26,29,28,14,0,3,1,30,26,32,29
142,Independent Olympic Participants (IOP) [IOP],1,0,1,2,0,0,0,0,1,0,1,2
143,Zambia (ZAM) [ZAM],12,0,1,1,0,0,0,0,12,0,1,1
144,Zimbabwe (ZIM) [ZIM],12,3,4,1,1,0,0,0,13,3,4,1
145,Mixed team (ZZX) [ZZX],3,8,5,4,0,0,0,0,3,8,5,4

Country          Armenia (ARM)
Summer                       5
Gold Summer                  1
Silver Summer                2
Bronze Summer                9
# Winter                     6
Gold Winter                  0
Silver Winter                0
Bronze Winter                0
# Games                     11
Gold                         1
Silver                       2
Bronze                       9
Name: 3, dtype: object

Afghanistan (AFG)
Algeria (ALG)
Argentina (ARG)
Armenia (ARM)
Australasia (ANZ) [ANZ]
Australia (AUS) [AUS] [Z]
Austria (AUT)
Azerbaijan (AZE)
Bahamas (BAH)
Bahrain (BRN)
Barbados (BAR) [BAR]
Belarus (BLR)
Belgium (BEL)
Bermuda (BER)
Bohemia (BOH) [BOH] [Z]
Botswana (BOT)
Brazil (BRA)
British West Indies (BWI) [BWI]
Bulgaria (BUL) [H]
Burundi (BDI)
Cameroon (CMR)
Canada (CAN)
Chile (CHI) [I]
China (CHN) [CHN]
Colombia (COL)
Costa Rica (CRC)
Ivory Coast (CIV) [CIV]
Croatia (CRO)
Cuba (CUB) [Z]
Cyprus (CYP)
Czech Republic (CZE) [CZE]
Czechoslovakia (TCH) [TCH]
Denmark (DEN) [Z]
Djibouti (DJI) [B]
Dominican Republic (DOM)
Ecuador (ECU)
Egypt (EGY) [EGY] [Z]
Eritrea (ERI)
Estonia (EST)
Ethiopia (ETH)
Finland (FIN)
France (FRA) [O] [P] [Z]
Gabon (GAB)
Georgia (GEO)
Germany (GER) [GER] [Z]
United Team of Germany (EUA) [EUA]
East Germany (GDR) [GDR]
West Germany (FRG) [FRG]
Ghana (GHA) [GHA]
Great Britain (GBR) [GBR] [Z]
Greece (GRE) [Z]
Grenada (GRN)
Guatemala (GUA)
Guyana (GUY) [GUY]
Haiti (HAI) [J]
Hong Kong (HKG) [HKG]
Hungary (HUN)
Iceland (ISL)
India (IND) [F]
Indonesia (INA)
Iran (IRI) [K]
Iraq (IRQ)
Ireland (IRL)
Israel (ISR)
Italy (ITA) [M] [S]
Jamaica (JAM) [JAM]
Japan (JPN)
Kazakhstan (KAZ)
Kenya (KEN)
North Korea (PRK)
South Korea (KOR)
Kuwait (KUW)
Kyrgyzstan (KGZ)
Latvia (LAT)
Lebanon (LIB)
Liechtenstein (LIE)
Lithuania (LTU)
Luxembourg (LUX) [O]
Macedonia (MKD)
Malaysia (MAS) [MAS]
Mauritius (MRI)
Mexico (MEX)
Moldova (MDA)
Mongolia (MGL)
Montenegro (MNE)
Morocco (MAR)
Mozambique (MOZ)
Namibia (NAM)
Netherlands (NED) [Z]
Netherlands Antilles (AHO) [AHO] [I]
New Zealand (NZL) [NZL]
Niger (NIG)
Nigeria (NGR)
Norway (NOR) [Q]
Pakistan (PAK)
Panama (PAN)
Paraguay (PAR)
Peru (PER) [L]
Philippines (PHI)
Poland (POL)
Portugal (POR)
Puerto Rico (PUR)
Qatar (QAT)
Romania (ROU)
Russia (RUS) [RUS]
Russian Empire (RU1) [RU1]
Soviet Union (URS) [URS]
Unified Team (EUN) [EUN]
Saudi Arabia (KSA)
Senegal (SEN)
Serbia (SRB) [SRB]
Serbia and Montenegro (SCG) [SCG]
Singapore (SIN)
Slovakia (SVK) [SVK]
Slovenia (SLO)
South Africa (RSA)
Spain (ESP) [Z]
Sri Lanka (SRI) [SRI]
Sudan (SUD)
Suriname (SUR) [E]
Sweden (SWE) [Z]
Switzerland (SUI)
Syria (SYR)
Chinese Taipei (TPE) [TPE] [TPE2]
Tajikistan (TJK)
Tanzania (TAN) [TAN]
Thailand (THA)
Togo (TOG)
Tonga (TGA)
Trinidad and Tobago (TRI) [TRI]
Tunisia (TUN)
Turkey (TUR)
Uganda (UGA)
Ukraine (UKR)
United Arab Emirates (UAE)
United States (USA) [P] [Q] [R] [Z]
Uruguay (URU)
Uzbekistan (UZB)
Venezuela (VEN)
Vietnam (VIE)
Virgin Islands (ISV)
Yugoslavia (YUG) [YUG]
Independent Olympic Participants (IOP) [IOP]
Zambia (ZAM) [ZAM]
Zimbabwe (ZIM) [ZIM]
Mixed team (ZZX) [ZZX]

In [7]:
data.head()

,Country,Summer,Gold Summer,Silver Summer,Bronze Summer,Total,# Winter,Gold Winter,Silver Winter,Bronze Winter,Total.1,# Games,Gold,Silver,Bronze,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

                    Country  Summer  Gold Summer  Silver Summer  \
141  Yugoslavia (YUG) [YUG]      16           26             29
142                     NaN       1            0              1
143                     NaN      12            0              1
144                     NaN      12            3              4
145                     NaN       3            8              5

     Bronze Summer  Total  # Winter  Gold Winter  Silver Winter  \
141             28     83        14            0              3
142              2      3         0            0              0
143              1      2         0            0              0
144              1      8         1            0              0
145              4     17         0            0              0

     Bronze Winter  Total.1  # Games  Gold  Silver  Bronze  Combined total
141              1        4       30    26      32      29              87
142              0        0        1     0       1       2               3
143              0        0       12     0       1       1               2
144              0        0       13     3       4       1               8
145              0        0        3     8       5       4              17

In [11]:
def first_country(name):
    for i in range(146):
        if name in data.loc[i][0]:
            print(data.loc[i])

In [12]:
first_country('India')

Country          India (IND) [F]
Summer                        23
Gold Summer                    9
Silver Summer                  6
Bronze Summer                 11
# Winter                       9
Gold Winter                    0
Silver Winter                  0
Bronze Winter                  0
# Games                       32
Gold                           9
Silver                         6
Bronze                        11
Name: 58, dtype: object

In [11]:
data.tail()

,Country,Summer,Gold Summer,Silver Summer,Bronze Summer,Total,# Winter,Gold Winter,Silver Winter,Bronze Winter,Total.1,# Games,Gold,Silver,Bronze,Combined total
141,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
142,NaN,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
143,NaN,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
144,NaN,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
145,NaN,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17

In [12]:
def gold_medals(df):
    return df.max()

In [13]:
gold_medals(data['Gold Summer'])

976

,Country,Summer,Gold Summer,Silver Summer,Bronze Summer,Total,# Winter,Gold Winter,Silver Winter,Bronze Winter,Total.1,# Games,Gold,Silver,Bronze,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
5,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
6,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
7,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
8,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
9,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
10,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
11,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
12,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
13,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
14,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
15,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
16,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
17,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
18,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
19,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
20,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
21,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
22,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
23,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
24,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
25,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
26,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
27,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
28,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
29,Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
117,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
118,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
119,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
120,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
121,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
122,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
123,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
124,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
125,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
126,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
127,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
128,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
129,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
130,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
131,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
132,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
133,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
134,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
135,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
136,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
137,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
138,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
139,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
140,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
141,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
142,NaN,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
143,NaN,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
144,NaN,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
145,NaN,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17

976